[package]
name = "ray_tracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.2"
fastrand = "1.9"
nannou = "0.18"
num_cpus = "1.15"
rayon = "1.7"
